apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-core-tls
spec:
  isCA: false
  duration: 2160h0m0s # 90d 
  renewBefore: 720h0m0s # 30d 
  commonName: {{ .Values.core.ingress.hostname }}
  dnsNames:
    - {{ .Values.core.ingress.hostname }}
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    kind: {{ .Values.core.ingress.issuer.kind }}
    name: {{ .Values.core.ingress.issuer.name }}
  secretName: {{ .Release.Name }}-core-tls