
# A secret of harbor admin password.
apiVersion: v1
kind: Secret
metadata:
  name: admin-core-secret
  namespace: {{ .Values.namespace }}
data:
  secret: {{ .Values.adminPassword }}
type: Opaque

---
# Cert issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: {{ .Values.namespace }}
spec:
  selfSigned: {}
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-public-certificate
  namespace: {{ .Values.namespace }}
spec:
  isCA: true
  duration: 2160h0m0s # 90d 2160h
  renewBefore: 168h0m0s # 7d 168h
  commonName: {{ .Values.commonName }}
  dnsNames:
    - {{ .Values.commonName }}
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: harbor-public-certificate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storageSize }}
---
# Full stack Harbor
apiVersion: goharbor.io/v1beta1
kind: HarborCluster
metadata:
  name: harborcluster-sample
  namespace: {{ .Values.namespace }}
spec:
  version: 2.3.0
  logLevel: debug
  imageSource:
    repository: ghcr.io/goharbor
  harborAdminPasswordRef: admin-core-secret
  externalURL: https://harb6.apps.opst.divyanshutech.xyz
  expose:
    core:
      ingress:
        host: harb6.apps.opst.divyanshutech.xyz
        controller: default
      tls:
        certificateRef: harbor-public-certificate
  internalTLS:
    enabled: {{ .Values.internalTLS }}
  portal: {}
  registry:
    metrics:
      enabled: true
  core:
    tokenIssuer:
      name: selfsigned-issuer
      kind: Issuer
    metrics:
      enabled: true
  exporter: {}
  database:
    kind: PostgreSQL
    spec:
      postgresql: 
        username: postgres # Required
        passwordRef: harbor-psql # Optional
        hosts:
          - host: harbor-psql.cluster.svc.cluster.local
            port: 5432 # Optional  
        sslMode: require
  storage:
    kind: FileSystem
    spec:
      fileSystem:
        registryPersistentVolume:
          claimName: harbor-registry
  cache:
    kind: "Redis"
    spec:
      redis:
        # Server host.
        host: harbor-redis-master.cluster.svc.cluster.local
        # Server port.
        port: 6379 # Required
        # For setting sentinel masterSet. 
        # Secret containing the password to use when connecting to the server.
        passwordRef: harbor-redis # Optional
        # Secret containing the client certificate to authenticate with.

