apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-harbor-operator
spec:
  destination: {{ toYaml .Values.operator.destination | nindent 4 }}
  project: {{ required .Values.operator.project "Required .Values.operator.project" }}
  syncPolicy: 
  # set automated to null if sync to be manual
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=false
      - Replace=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  source:
    path: {{ .Values.operator.sourcePath }}
    repoURL: '{{ .Values.operator.repoURL }}'
    targetRevision: {{ .Values.operator.targetRevision }}   

