apiVersion: v2
# Harbor cluster on Openshift
appVersion: 2.3.3
description: 'Harbor cluster deployment on Openshift'
name: harbor-cluster
dependencies:
- name: redis
  version: "15.3.2"  
  repository: "https://charts.bitnami.com/bitnami"
# Chart version
version: 1.0.0
