apiVersion: v2
# Harbor cluster on Openshift
appVersion: 2.3.3
description: 'Harbor cluster deployment on Openshift'
name: harbor-cluster
dependencies:


- name: postgres-operator
  version: "1.7.0"
  repository: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator/"
  condition: postgres-operator.enabled
- name: redis
  version: "15.3.2"  
  repository: "https://charts.bitnami.com/bitnami"
- name: external-dns
  version: "5.4.12"  
  repository: "https://charts.bitnami.com/bitnami"
  condition: external-dns.enabled
# Chart version
version: 1.0.0
