openshift:
  scc:
    nonroot: false #if you want to add nonroot scc to default sa
  patchNs:
    enabled: true #if you want to patch ns to allow uid and fsgroup 10000
  zalandoOperator:
    createAdditionalRBAC: true
    

external-dns:
  enabled: true
  podSecurityContext:
    fsGroup: null
    runAsUser: null
  provider: aws
  txtOwnerId: Z0465218S9L230WGWNJK
  domainFilters: 
    - thadvatys.com
  txtPrefix: txt
  aws:
    zoneType: public
    credentials:
      secretName: "aws-config-secret"
    vault:
      address: "http://vault.vault.svc.cluster.local:8200"
      path: kubernetes
      role: webhook
      skipVerify: "true"
      secret:
        location: secret/data/aws/config #aws secrets in vault
        credentials: credentials #name of aws credentials's key in vault secret

version: 2.3.3
logLevel: debug #info

core:
  ingress:
    hostname: harbor.example.com
    class: nginx
    issuer:
      create: false
      kind: Issuer #ClusterIssuer
      name: letsencrypt-production-http
      spec:
        acme:
          email: tarik.haddouchi@advatys.com
          server: https://acme-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: harbor-issuer-account-key
          solvers:
          - http01:
             ingress:
               class: nginx
               
  oidc:
    enabled: true
    name: "keycloak"
    endpoint: "http://oidcsubdomain.example.org/auth/realms/harbor"
    clientId: "harbor"
    groupsClaim: "harbor"
    adminGroup: "/admin" 
    scope: "openid,offline_access,profile,email"
    verifyCert: false
        

registry:
  storage:
    registryPersistentVolume:
      size: 20Gi



trivy:
  storage:
    cachePersistentVolume:
      size: 10Gi
    reportsPersistentVolume:
      size: 10Gi

redis:
  master:
    persistence:
      size: 5Gi
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
  replica:
    persistence:
      size: 8Gi
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false 
  
postgresql:
  operatorVersion: "1.7.0"
  storage: 1Gi
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 250Mi