openshift:
  patchNs:
    enabled: true

external-dns:
  enabled: true
  podSecurityContext:
    fsGroup: 10000
    runAsUser: 10000
  provider: aws
  txtOwnerId: Z0465218S9L230WGWNJK
  domainFilters: 
    - thadvatys.com
  aws:
    zoneType: public
    secretName: "aws-config-secret"
    vault:
      address: "http://vault.vault.svc.cluster.local:8200"
      path: kubernetes
      role: webhook
      skipVerify: "true"
      secret:
        location: secret/data/aws/config #aws secrets in vault
        accessKey: aws_access_key_id #name of accesskey's key in vault secret
        secretKey: aws_secret_access_key #name of secretkey's key in vault secret
        credentials: credentials

version: 2.3.3


core:
  ingress:
    hostname: harbor.example.com
    class: nginx
    issuer:
      create: false
      kind: Issuer #ClusterIssuer
      name: selfsigned-issuer #letsencrypt-production-http

registry:
  storage:
    registryPersistentVolume:
      size: 20Gi



trivy:
  storage:
    cachePersistentVolume:
      size: 10Gi
    reportsPersistentVolume:
      size: 10Gi

postgresql:
  containerSecurityContext: 
    enabled: false
  securityContext:
    enabled: false
  shmVolume:
    chmod:
      enabled: false  
  tls:
    ## @param tls.enabled Enable TLS traffic support
    ##  
    enabled: false
    ## @param tls.autoGenerated Generate automatically self-signed TLS certificates
    ##
    autoGenerated: false
  volumePermissions:
    enabled: true
    securityContext:
      runAsUser: "auto"
  postgresqlDatabase: "core"
  persistence:
    size: 7Gi
  serviceAccount:
    enabled: true
  psp:
    create: false
  rbac:
    create: true

redis:
  master:
    persistence:
      size: 5Gi
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
  replica:
    persistence:
      size: 8Gi
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false 
  
