operator:
  project: default
  destination:
    namespace: harbor
    name: ''
    server: https://kubernetes.default.svc
  # namespace in which opendistro to be installed in
  source:
    path: charts/harbor-operator  
    repoURL: 'https://github.com/goharbor/harbor-operator.git'
    targetRevision: v1.1.1
    helm:
      values: |-
        installCRDs: true
        podSecurityContext:
          runAsUser: null
          runAsNonRoot: true

        leaderElection:
          namespace: "harbor"


cluster:
  project: default
  destination:
    namespace: harbor
    name: ''
    server: https://kubernetes.default.svc
  # namespace in which opendistro to be installed in
  source:
    path: charts/harbor-operator  
    repoURL: 'https://github.com/goharbor/harbor-operator.git'
    targetRevision: v1.1.1
    helm:
      redisOperatorInstall: false
      minioOperatorInstall: false
      postgresOperatorInstall: false

  appName: harbor-cluster
  # namespace in which opendistro to be installed in
  destNamespace: harbor
  destinationServer: https://kubernetes.default.svc
  appNamespace: default
  prune: false
  selfHeal: false
  syncOptions:
    - Validate=false
    - PruneLast=false
    - Replace=false
    - CreateNamespace=false
    - ApplyOutOfSyncOnly=false
  sourcePath: harbor-cluster-components 
  # official repo of opendistro
  repoURL: 'https://github.com/advatys/harbor.git'
  targetRevision: main
