 {{- if index .Values "external-dns" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "external-dns" "aws" "secretName" }}
  annotations:
    vault.security.banzaicloud.io/vault-addr: '{{ index .Values "external-dns" "aws" "vault" "address" }}'
    vault.security.banzaicloud.io/vault-path: {{ index .Values "external-dns" "aws" "vault" "path" }}
    vault.security.banzaicloud.io/vault-role: {{ index .Values "external-dns" "aws" "vault" "role" }}
    vault.security.banzaicloud.io/vault-skip-verify: '{{ index .Values "external-dns" "aws" "vault" "skipVerify" }}'
type: Opaque
stringData:
  accessKey: vault:{{ index .Values "external-dns" "aws" "vault" "secret" "location" }}#{{ index .Values "external-dns" "aws" "vault" "secret" "accessKey" }}
  secretKey: vault:{{ index .Values "external-dns" "aws" "vault" "secret" "location" }}#{{ index .Values "external-dns" "aws" "vault" "secret" "secretKey" }}
 {{- end }}