 {{- if .Values.external-dns.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.external-dns.aws.secretName }}
  annotations:
    vault.security.banzaicloud.io/vault-addr: '{{ .Values.external-dns.aws.vault.address }}'
    vault.security.banzaicloud.io/vault-path: {{ .Values.external-dns.aws.vault.path }}
    vault.security.banzaicloud.io/vault-role: {{ .Values.external-dns.aws.vault.role }}
    vault.security.banzaicloud.io/vault-skip-verify: '{{ .Values.external-dns.aws.vault.skipVerify }}'
type: Opaque
stringData:
  accessKey: vault:{{ .Values.external-dns.aws.vault.secret.location }}#{{ .Values.external-dns.aws.vault.secret.accessKey }}
  secretKey: vault:{{ .Values.external-dns.aws.vault.secret.location }}#{{ .Values.external-dns.aws.vault.secret.secretKey }}
 {{- end }}