
# Full stack Harbor
apiVersion: goharbor.io/v1beta1
kind: HarborCluster
metadata:
  name: {{ .Release.Name }}

spec:
  version: {{ .Values.version }}
  logLevel: debug #info
  harborAdminPasswordRef: {{ .Release.Name }}-admin-core-secret
  externalURL: https://{{ .Values.core.ingress.hostname }} #{{ .Values.coreHostName }}
  expose:
    core:
      ingress:
        host: {{ .Values.core.ingress.hostname }}
        controller: default
        annotations:
          kubernetes.io/ingress.class: "{{ .Values.core.ingress.class }}"
          ingress.kubernetes.io/force-ssl-redirect: "true"
      tls:
        certificateRef: {{ .Release.Name }}-core-tls

  internalTLS:
    enabled: false
  portal: {}
  registry:
    metrics:
      enabled: true

  core:
    tokenIssuer:
      name: selfsigned-issuer
      kind: Issuer
    metrics:
      enabled: true
  exporter: {}

  # Database configuration
  # https://github.com/goharbor/harbor-operator/blob/master/docs/CRD/custom-resource-definition.md#standard-database
  
  database:
    kind: Zlando/PostgreSQL
    spec:
      zlandoPostgreSql:
        operatorVersion: "1.7.0"
        storage: 1Gi
        replicas: 2
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 250Mi
  
  storage:
    kind: FileSystem
    spec:
      # Filesystem storage configuration
      # https://github.com/goharbor/harbor-operator/blob/master/docs/CRD/custom-resource-definition.md#filesystem
      fileSystem:
        registryPersistentVolume:
          claimName: {{ .Release.Name }}-registry


  cache:
    kind: "Redis"
    spec:
      redis:
        # Server host.
        host: {{ .Values.redis.fullnameOverride }}-master
        # Server port.
        port: 6379 # Required
        # For setting sentinel masterSet. 
        # Secret containing the password to use when connecting to the server.
        passwordRef: {{ .Values.redis.fullnameOverride }} # Optional
        # Secret containing the client certificate to authenticate with.


  trivy:
    skipUpdate: false
    storage:
      cachePersistentVolume:
        claimName: {{ .Release.Name }}-harbor-trivy-cache
      reportsPersistentVolume:
        claimName: {{ .Release.Name }}-harbor-trivy-reports