# Cert issuer
apiVersion: cert-manager.io/v1
kind: {{ .Values.core.ingress.issuer.kind }}
metadata:
  name: {{ .Values.core.ingress.issuer.name }}
spec:
{{ toYaml .Values.core.ingress.issuer.spec | indent 2 }}
