apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-postgres-operator-additional
rules:
- apiGroups:
  - ""
  resources:
  - endpoints/restricted
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-postgres-operator-additional
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-postgres-operator-additional
subjects:
- kind: ServiceAccount
  name: postgres-pod
  namespace: {{ .Release.Namespace }}