
project: default
destination:
  namespace: harbor-operator
  name: ''
  server: https://kubernetes.default.svc

source:
  path: charts/harbor-operator  
  repoURL: 'https://github.com/goharbor/harbor-operator.git'
  targetRevision: v1.1.1
  helm:
    values: |-
      installCRDs: true
      podSecurityContext:
        runAsUser: null
        runAsNonRoot: true
      minio-operator:
        enabled: false    
      leaderElection:
        namespace: "harbor-operator"



