apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-operator
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination: {{ toYaml .Values.destination | nindent 4 }}
  project: {{ .Values.project }}
  syncPolicy: 
  # set automated to null if sync to be manual
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=false
      - Replace=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  source: {{ toYaml .Values.source | nindent 4 }}


